---
- name: F5 Software Upgrade Pre-Check
  hosts: your_f5_devices
  connection: local
  gather_facts: no
  vars_files:
    - vars/f5_upgrade_vars.yml

  tasks:
    - name: Pre-check connectivity to F5 device
      ansible.builtin.wait_for:
        port: 22
        timeout: 30
        host: "{{ inventory_hostname }}"
        state: started
      delegate_to: localhost
      ignore_errors: true
      register: ssh_check

    - name: Fail if SSH connectivity check failed
      ansible.builtin.fail:
        msg: "Pre-check failed: Could not establish SSH connectivity to {{ inventory_hostname }}."
      when: ssh_check.failed

    - name: Get F5 facts and save initial boot location
      f5networks.f5_modules.bigip_facts:
      register: initial_facts
      
    - name: Set fact for initial boot location
      ansible.builtin.set_fact:
        initial_boot_location: "{{ initial_facts.ansible_facts.f5_active_volume }}"

    - name: Check if the ISO file exists on the Ansible control node
      ansible.builtin.stat:
        path: "/path/to/your/iso/{{ iso_file }}"
      delegate_to: localhost
      run_once: true
      register: iso_stat_result

    - name: Fail if the ISO file is missing from the Ansible control node
      ansible.builtin.fail:
        msg: "Pre-check failed: The ISO file {{ iso_file }} was not found on the Ansible control node at the specified path."
      when: not iso_stat_result.stat.exists

    - name: Check if the F5 is in an active state
      f5networks.f5_modules.bigip_command:
        commands:
          - "tmsh show sys ha-status"
      register: ha_status_check
      
    - name: Fail if the F5 is not in a 'running' or 'active' state
      ansible.builtin.fail:
        msg: "Pre-check failed: F5 device {{ inventory_hostname }} is not in an active state. HA status: {{ ha_status_check.stdout }}"
      when: "'running' not in ha_status_check.stdout and 'active' not in ha_status_check.stdout"

    - name: Print pre-check results
      ansible.builtin.debug:
        msg: |
          "F5 Pre-Check Report for {{ inventory_hostname }}:
          ------------------------------------------
          Current Active Boot Location: {{ initial_boot_location }}
          ISO File on Ansible Control Node: {{ iso_file }} exists: {{ iso_stat_result.stat.exists }}"
